# Generated by Django 5.0.5 on 2024-05-07 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(blank=True, max_length=200, null=True)),
                ('matricula_aluno', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade_aluno', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('nome_turma', models.CharField(blank=True, max_length=200, null=True)),
                ('aluno_turma', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='presenteApp.aluno')),
            ],
        ),
    ]
